name: ammommyappgp
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_pw_validator: ^1.5.0
  provider: ^6.0.5
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.17.0
  firebase_core: ^2.11.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  flutter_cupertino_date_picker: ^1.0.26+2
  flutter_localizations:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  hijri: ^3.0.0
  hijri_picker: ^3.0.0
  date_time_picker: ^2.1.0
  jiffy: ^5.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: ABeeZee
      fonts: 
        - asset: assets/fonts/ABeeZeeRegular.ttf
          weight: 400
        - asset: assets/fonts/ABeeZeeItalic.ttf
          weight: 400
    - family: Montserrat
      fonts: 
        - asset: assets/fonts/MontserratRegular.ttf
          weight: 400
        - asset: assets/fonts/MontserratBold.ttf
          weight: 700
    - family: MonteCarlo
      fonts: 
        - asset: assets/fonts/MonteCarloRegular.ttf
          weight: 400
